### ISSUE TITLE
Bishops and rooks are not printing on the board

### ISSUE THREAD

**Issue by Garic152** [Garic152/pythonchess#1]
When printing the board, the bishops and rook don't get printed but they still can attack other squares.

**Comment by eduardChalovski** [comment]
is it up to date? it works when I test it
![Screenshot bishops and rooks](https://user-images.githubusercontent.com/85243017/236647926-500a38b9-fc70-49c0-a56d-157ef031a3bd.png)

**Comment by PraxTube** [comment]
Seems to work in my case too.

```
N-12:03 $ python main.py 
Side to move: b
Castling: 1111
1   r . . . . . . . 
2   . . . . . . . . 
3   . . . . . . . . 
4   . . . q . . . . 
5   . . . . . . . . 
6   . . . . . . . . 
7   . . . . . . b . 
8   . . . . . . . . 

    A B C D E F G H
1   x x x x x x x x 
2   x x . x . x . . 
3   x . x x x . . . 
4   x x x x x x x x 
5   x . x x x . . . 
6   x x . x . x . x 
7   x . . x . . x . 
8   x . . x . x . x 

    A B C D E F G H
```

Perhaps you made local changes that introduces a bug. I would suggest checking `git status` or if you made changes you want to revert using `git reset --hard` (though be careful, any non commited changes will be reset!).
