### ISSUE TITLE
make_move wrong else statement

### ISSUE THREAD

**Issue by Garic152** [Garic152/pythonchess#12]
The only else statement in make_move should be the else at the bottom which returns that the move is legal
@eduardChalovski please fix this issue asap because it breaks the legal move check function

https://github.com/Garic152/pythonchess/blame/bfc4e7a77f233b2a0a90648cf2875fa619b08c9d/main.py#LL743-L760C43

**Comment by PraxTube** [comment]
You might be able to use guard clauses too.
