### ISSUE TITLE
Castling is not getting recognized when loading board

### ISSUE THREAD

**Issue by Garic152** [Garic152/pythonchess#19]
The print_stats function prints 1111 regardless of the board state.
Should be fixed for optimal results.

**Comment by Luweren** [comment]
for me the castling prints correctly after a correct castle
![image](https://github.com/Garic152/pythonchess/assets/64533550/c18a70bc-c672-40ff-9821-6394c5a92da9)
![image](https://github.com/Garic152/pythonchess/assets/64533550/ad86e78a-3f38-4480-aa9b-36c290a83317)
