### ISSUE TITLE
Benchmarks in docs subfolder

### ISSUE THREAD

**Issue by PraxTube** [Garic152/pythonchess#9]
It would be very useful if there were benchmarks in a .txt or .csv or similar format in a subfolder like `docs` or `benchmarks`. This makes it nice to compare and track progress throughout the project (and compare to other projects).

**Comment by PraxTube** [comment]
How do you even benchmark the engine? I can't find a benchmark script of similar.

**Comment by Luweren** [comment]
added basic benchmarking in a txt file

'w' = overwrite mode
'a' = append mode

**Comment by PraxTube** [comment]
@Luweren where did you add that? I can't find it in either the main branch nor in any PR's. Also perhaps you could add a README.md entry that explains how to use/run the benchmarks.
